/*
# Even Fibonacci numbers  
# Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include<stdio.h>

int main(){
    unsigned long long a = 0;
    unsigned long long b = 1;
    unsigned long long c = 2;
    unsigned long long res = 0;
    while(c < 4000000){
        if(c%2 == 0){
            res += c;
        }
        a = c;
        c = b+c;
        b = a;
    }
    printf("%llu", res);
    return 0;
}